// Copyright 2026 the Execution Tape Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

// @generated by execution_tape_codegen. Do not edit by hand.

#[rustfmt::skip]
pub(crate) fn decode_instr(opcode: Opcode, r: &mut Reader<'_>) -> Result<Instr, DecodeError> {
    Ok(match opcode {
        Opcode::Nop => Instr::Nop,
        Opcode::Mov => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let src = crate::codec_primitives::read_reg(r)?;
            Instr::Mov {
                dst,
                src,
            }
        },
        Opcode::Trap => {
            let code = crate::codec_primitives::read_u32_uleb(r)?;
            Instr::Trap {
                code,
            }
        },
        Opcode::ConstUnit => {
            let dst = crate::codec_primitives::read_reg(r)?;
            Instr::ConstUnit {
                dst,
            }
        },
        Opcode::ConstBool => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let imm = crate::codec_primitives::read_bool_u8(r)?;
            Instr::ConstBool {
                dst,
                imm,
            }
        },
        Opcode::ConstI64 => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let imm = crate::codec_primitives::read_i64_sleb(r)?;
            Instr::ConstI64 {
                dst,
                imm,
            }
        },
        Opcode::ConstU64 => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let imm = crate::codec_primitives::read_u64_uleb(r)?;
            Instr::ConstU64 {
                dst,
                imm,
            }
        },
        Opcode::ConstF64 => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let bits = crate::codec_primitives::read_u64_le(r)?;
            Instr::ConstF64 {
                dst,
                bits,
            }
        },
        Opcode::ConstDecimal => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let mantissa = crate::codec_primitives::read_i64_sleb(r)?;
            let scale = crate::codec_primitives::read_u8_raw(r)?;
            Instr::ConstDecimal {
                dst,
                mantissa,
                scale,
            }
        },
        Opcode::ConstPool => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let idx = ConstId(crate::codec_primitives::read_u32_uleb(r)?);
            Instr::ConstPool {
                dst,
                idx,
            }
        },
        Opcode::DecAdd => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::DecAdd {
                dst,
                a,
                b,
            }
        },
        Opcode::DecSub => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::DecSub {
                dst,
                a,
                b,
            }
        },
        Opcode::DecMul => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::DecMul {
                dst,
                a,
                b,
            }
        },
        Opcode::F64Add => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::F64Add {
                dst,
                a,
                b,
            }
        },
        Opcode::F64Sub => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::F64Sub {
                dst,
                a,
                b,
            }
        },
        Opcode::F64Mul => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::F64Mul {
                dst,
                a,
                b,
            }
        },
        Opcode::I64Add => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::I64Add {
                dst,
                a,
                b,
            }
        },
        Opcode::I64Sub => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::I64Sub {
                dst,
                a,
                b,
            }
        },
        Opcode::I64Mul => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::I64Mul {
                dst,
                a,
                b,
            }
        },
        Opcode::U64Add => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::U64Add {
                dst,
                a,
                b,
            }
        },
        Opcode::U64Sub => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::U64Sub {
                dst,
                a,
                b,
            }
        },
        Opcode::U64Mul => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::U64Mul {
                dst,
                a,
                b,
            }
        },
        Opcode::U64And => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::U64And {
                dst,
                a,
                b,
            }
        },
        Opcode::U64Or => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::U64Or {
                dst,
                a,
                b,
            }
        },
        Opcode::I64Eq => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::I64Eq {
                dst,
                a,
                b,
            }
        },
        Opcode::I64Lt => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::I64Lt {
                dst,
                a,
                b,
            }
        },
        Opcode::U64Eq => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::U64Eq {
                dst,
                a,
                b,
            }
        },
        Opcode::U64Lt => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::U64Lt {
                dst,
                a,
                b,
            }
        },
        Opcode::U64Xor => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::U64Xor {
                dst,
                a,
                b,
            }
        },
        Opcode::U64Shl => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::U64Shl {
                dst,
                a,
                b,
            }
        },
        Opcode::U64Shr => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::U64Shr {
                dst,
                a,
                b,
            }
        },
        Opcode::U64Gt => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::U64Gt {
                dst,
                a,
                b,
            }
        },
        Opcode::BoolNot => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            Instr::BoolNot {
                dst,
                a,
            }
        },
        Opcode::U64Le => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::U64Le {
                dst,
                a,
                b,
            }
        },
        Opcode::U64Ge => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::U64Ge {
                dst,
                a,
                b,
            }
        },
        Opcode::I64And => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::I64And {
                dst,
                a,
                b,
            }
        },
        Opcode::U64ToI64 => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            Instr::U64ToI64 {
                dst,
                a,
            }
        },
        Opcode::I64ToU64 => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            Instr::I64ToU64 {
                dst,
                a,
            }
        },
        Opcode::I64Or => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::I64Or {
                dst,
                a,
                b,
            }
        },
        Opcode::I64Xor => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::I64Xor {
                dst,
                a,
                b,
            }
        },
        Opcode::Select => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let cond = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::Select {
                dst,
                cond,
                a,
                b,
            }
        },
        Opcode::I64Gt => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::I64Gt {
                dst,
                a,
                b,
            }
        },
        Opcode::I64Le => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::I64Le {
                dst,
                a,
                b,
            }
        },
        Opcode::I64Ge => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::I64Ge {
                dst,
                a,
                b,
            }
        },
        Opcode::I64Shl => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::I64Shl {
                dst,
                a,
                b,
            }
        },
        Opcode::I64Shr => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::I64Shr {
                dst,
                a,
                b,
            }
        },
        Opcode::Br => {
            let cond = crate::codec_primitives::read_reg(r)?;
            let pc_true = crate::codec_primitives::read_u32_uleb(r)?;
            let pc_false = crate::codec_primitives::read_u32_uleb(r)?;
            Instr::Br {
                cond,
                pc_true,
                pc_false,
            }
        },
        Opcode::Jmp => {
            let pc_target = crate::codec_primitives::read_u32_uleb(r)?;
            Instr::Jmp {
                pc_target,
            }
        },
        Opcode::Call => {
            let eff_out = crate::codec_primitives::read_reg(r)?;
            let func_id = FuncId(crate::codec_primitives::read_u32_uleb(r)?);
            let eff_in = crate::codec_primitives::read_reg(r)?;
            let args = crate::codec_primitives::read_reg_list(r)?;
            let rets = crate::codec_primitives::read_reg_list(r)?;
            Instr::Call {
                eff_out,
                func_id,
                eff_in,
                args,
                rets,
            }
        },
        Opcode::Ret => {
            let eff_in = crate::codec_primitives::read_reg(r)?;
            let rets = crate::codec_primitives::read_reg_list(r)?;
            Instr::Ret {
                eff_in,
                rets,
            }
        },
        Opcode::HostCall => {
            let eff_out = crate::codec_primitives::read_reg(r)?;
            let host_sig = HostSigId(crate::codec_primitives::read_u32_uleb(r)?);
            let eff_in = crate::codec_primitives::read_reg(r)?;
            let args = crate::codec_primitives::read_reg_list(r)?;
            let rets = crate::codec_primitives::read_reg_list(r)?;
            Instr::HostCall {
                eff_out,
                host_sig,
                eff_in,
                args,
                rets,
            }
        },
        Opcode::TupleNew => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let values = crate::codec_primitives::read_reg_list(r)?;
            Instr::TupleNew {
                dst,
                values,
            }
        },
        Opcode::TupleGet => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let tuple = crate::codec_primitives::read_reg(r)?;
            let index = crate::codec_primitives::read_u32_uleb(r)?;
            Instr::TupleGet {
                dst,
                tuple,
                index,
            }
        },
        Opcode::StructNew => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let type_id = TypeId(crate::codec_primitives::read_u32_uleb(r)?);
            let values = crate::codec_primitives::read_reg_list(r)?;
            Instr::StructNew {
                dst,
                type_id,
                values,
            }
        },
        Opcode::StructGet => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let st = crate::codec_primitives::read_reg(r)?;
            let field_index = crate::codec_primitives::read_u32_uleb(r)?;
            Instr::StructGet {
                dst,
                st,
                field_index,
            }
        },
        Opcode::ArrayNew => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let elem_type_id = ElemTypeId(crate::codec_primitives::read_u32_uleb(r)?);
            let values_count = crate::codec_primitives::read_u32_uleb(r)?;
            let mut values = Vec::with_capacity(values_count as usize);
            for _ in 0..(values_count as usize) {
                values.push(crate::codec_primitives::read_reg(r)?);
            }
            let len = values_count;
            Instr::ArrayNew {
                dst,
                elem_type_id,
                len,
                values,
            }
        },
        Opcode::ArrayLen => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let arr = crate::codec_primitives::read_reg(r)?;
            Instr::ArrayLen {
                dst,
                arr,
            }
        },
        Opcode::ArrayGet => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let arr = crate::codec_primitives::read_reg(r)?;
            let index = crate::codec_primitives::read_reg(r)?;
            Instr::ArrayGet {
                dst,
                arr,
                index,
            }
        },
        Opcode::TupleLen => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let tuple = crate::codec_primitives::read_reg(r)?;
            Instr::TupleLen {
                dst,
                tuple,
            }
        },
        Opcode::StructFieldCount => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let st = crate::codec_primitives::read_reg(r)?;
            Instr::StructFieldCount {
                dst,
                st,
            }
        },
        Opcode::ArrayGetImm => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let arr = crate::codec_primitives::read_reg(r)?;
            let index = crate::codec_primitives::read_u32_uleb(r)?;
            Instr::ArrayGetImm {
                dst,
                arr,
                index,
            }
        },
        Opcode::BytesLen => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let bytes = crate::codec_primitives::read_reg(r)?;
            Instr::BytesLen {
                dst,
                bytes,
            }
        },
        Opcode::StrLen => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let s = crate::codec_primitives::read_reg(r)?;
            Instr::StrLen {
                dst,
                s,
            }
        },
        Opcode::I64Div => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::I64Div {
                dst,
                a,
                b,
            }
        },
        Opcode::I64Rem => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::I64Rem {
                dst,
                a,
                b,
            }
        },
        Opcode::U64Div => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::U64Div {
                dst,
                a,
                b,
            }
        },
        Opcode::U64Rem => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::U64Rem {
                dst,
                a,
                b,
            }
        },
        Opcode::I64ToF64 => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            Instr::I64ToF64 {
                dst,
                a,
            }
        },
        Opcode::U64ToF64 => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            Instr::U64ToF64 {
                dst,
                a,
            }
        },
        Opcode::F64ToI64 => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            Instr::F64ToI64 {
                dst,
                a,
            }
        },
        Opcode::F64ToU64 => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            Instr::F64ToU64 {
                dst,
                a,
            }
        },
        Opcode::DecToI64 => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            Instr::DecToI64 {
                dst,
                a,
            }
        },
        Opcode::DecToU64 => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            Instr::DecToU64 {
                dst,
                a,
            }
        },
        Opcode::I64ToDec => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let scale = crate::codec_primitives::read_u8_raw(r)?;
            Instr::I64ToDec {
                dst,
                a,
                scale,
            }
        },
        Opcode::U64ToDec => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let scale = crate::codec_primitives::read_u8_raw(r)?;
            Instr::U64ToDec {
                dst,
                a,
                scale,
            }
        },
        Opcode::BytesEq => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::BytesEq {
                dst,
                a,
                b,
            }
        },
        Opcode::StrEq => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::StrEq {
                dst,
                a,
                b,
            }
        },
        Opcode::BytesConcat => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::BytesConcat {
                dst,
                a,
                b,
            }
        },
        Opcode::StrConcat => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::StrConcat {
                dst,
                a,
                b,
            }
        },
        Opcode::BytesGet => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let bytes = crate::codec_primitives::read_reg(r)?;
            let index = crate::codec_primitives::read_reg(r)?;
            Instr::BytesGet {
                dst,
                bytes,
                index,
            }
        },
        Opcode::BytesGetImm => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let bytes = crate::codec_primitives::read_reg(r)?;
            let index = crate::codec_primitives::read_u32_uleb(r)?;
            Instr::BytesGetImm {
                dst,
                bytes,
                index,
            }
        },
        Opcode::BytesSlice => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let bytes = crate::codec_primitives::read_reg(r)?;
            let start = crate::codec_primitives::read_reg(r)?;
            let end = crate::codec_primitives::read_reg(r)?;
            Instr::BytesSlice {
                dst,
                bytes,
                start,
                end,
            }
        },
        Opcode::StrSlice => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let s = crate::codec_primitives::read_reg(r)?;
            let start = crate::codec_primitives::read_reg(r)?;
            let end = crate::codec_primitives::read_reg(r)?;
            Instr::StrSlice {
                dst,
                s,
                start,
                end,
            }
        },
        Opcode::StrToBytes => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let s = crate::codec_primitives::read_reg(r)?;
            Instr::StrToBytes {
                dst,
                s,
            }
        },
        Opcode::BytesToStr => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let bytes = crate::codec_primitives::read_reg(r)?;
            Instr::BytesToStr {
                dst,
                bytes,
            }
        },
        Opcode::F64Div => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::F64Div {
                dst,
                a,
                b,
            }
        },
        Opcode::F64Eq => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::F64Eq {
                dst,
                a,
                b,
            }
        },
        Opcode::F64Lt => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::F64Lt {
                dst,
                a,
                b,
            }
        },
        Opcode::F64Gt => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::F64Gt {
                dst,
                a,
                b,
            }
        },
        Opcode::F64Le => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::F64Le {
                dst,
                a,
                b,
            }
        },
        Opcode::F64Ge => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::F64Ge {
                dst,
                a,
                b,
            }
        },
        Opcode::BoolAnd => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::BoolAnd {
                dst,
                a,
                b,
            }
        },
        Opcode::BoolOr => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::BoolOr {
                dst,
                a,
                b,
            }
        },
        Opcode::BoolXor => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::BoolXor {
                dst,
                a,
                b,
            }
        },
        Opcode::F64Neg => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            Instr::F64Neg {
                dst,
                a,
            }
        },
        Opcode::F64Abs => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            Instr::F64Abs {
                dst,
                a,
            }
        },
        Opcode::F64Min => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::F64Min {
                dst,
                a,
                b,
            }
        },
        Opcode::F64Max => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::F64Max {
                dst,
                a,
                b,
            }
        },
        Opcode::F64MinNum => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::F64MinNum {
                dst,
                a,
                b,
            }
        },
        Opcode::F64MaxNum => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::F64MaxNum {
                dst,
                a,
                b,
            }
        },
        Opcode::F64Rem => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            let b = crate::codec_primitives::read_reg(r)?;
            Instr::F64Rem {
                dst,
                a,
                b,
            }
        },
        Opcode::F64ToBits => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            Instr::F64ToBits {
                dst,
                a,
            }
        },
        Opcode::F64FromBits => {
            let dst = crate::codec_primitives::read_reg(r)?;
            let a = crate::codec_primitives::read_reg(r)?;
            Instr::F64FromBits {
                dst,
                a,
            }
        },
    })
}
