// Copyright 2026 the Execution Tape Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

// @generated by execution_tape_codegen. Do not edit by hand.

use crate::bytecode::Instr;
use crate::program::{ConstId, ElemTypeId, HostSigId, TypeId};
use crate::value::FuncId;

#[rustfmt::skip]
pub(crate) fn visit_pcs(instr: &Instr, mut f: impl FnMut(u32)) {
    match instr {
        Instr::Br { pc_true, pc_false, .. } => {
            f(*pc_true);
            f(*pc_false);
        }
        Instr::Jmp { pc_target, .. } => {
            f(*pc_target);
        }
        _ => {}
    }
}

#[rustfmt::skip]
pub(crate) fn visit_const_ids(instr: &Instr, mut f: impl FnMut(ConstId)) {
    if let Instr::ConstPool { idx, .. } = instr {
        f(*idx);
    }
}

#[rustfmt::skip]
pub(crate) fn visit_func_ids(instr: &Instr, mut f: impl FnMut(FuncId)) {
    if let Instr::Call { func_id, .. } = instr {
        f(*func_id);
    }
}

#[rustfmt::skip]
pub(crate) fn visit_host_sig_ids(instr: &Instr, mut f: impl FnMut(HostSigId)) {
    if let Instr::HostCall { host_sig, .. } = instr {
        f(*host_sig);
    }
}

#[rustfmt::skip]
pub(crate) fn visit_type_ids(instr: &Instr, mut f: impl FnMut(TypeId)) {
    if let Instr::StructNew { type_id, .. } = instr {
        f(*type_id);
    }
}

#[rustfmt::skip]
pub(crate) fn visit_elem_type_ids(instr: &Instr, mut f: impl FnMut(ElemTypeId)) {
    if let Instr::ArrayNew { elem_type_id, .. } = instr {
        f(*elem_type_id);
    }
}

