// Copyright 2026 the Execution Tape Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

// @generated by execution_tape_codegen. Do not edit by hand.

/// Operand kinds used by the opcode table.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum OperandKind {
    /// A single virtual register.
    Reg,
    /// A list of virtual registers.
    RegList,
    /// A bytecode PC (byte offset).
    Pc,
    /// An immediate `bool`.
    ImmBool,
    /// An immediate `u8`.
    ImmU8,
    /// An immediate `u32`.
    ImmU32,
    /// An immediate `i64`.
    ImmI64,
    /// An immediate `u64`.
    ImmU64,
    /// A constant pool index.
    ConstId,
    /// A function index.
    FuncId,
    /// A host signature index.
    HostSigId,
    /// A struct type index.
    TypeId,
    /// An array element type index.
    ElemTypeId,
}

/// Operand roles used by the opcode table.
///
/// Roles are a best-effort description for disassembly/tooling.
#[allow(missing_docs, reason = "generated")]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum OperandRole {
    Dst,
    Src,
    A,
    B,
    Cond,
    PcTrue,
    PcFalse,
    PcTarget,
    Imm,
    Bits,
    Mantissa,
    Scale,
    TrapCode,
    Const,
    Func,
    HostSig,
    Type,
    ElemType,
    EffIn,
    EffOut,
    Args,
    Rets,
    Values,
    Tuple,
    St,
    Arr,
    Index,
    FieldIndex,
    Start,
    End,
    Bytes,
    S,
}

/// Operand encodings used by the bytecode codec.
#[allow(missing_docs, reason = "generated")]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum OperandEncoding {
    RegU32Uleb,
    RegListU32UlebCountThenRegs,
    BoolU8,
    U8Raw,
    U32Uleb,
    I64Sleb,
    U64Uleb,
    U64Le,
}

/// Operand access for register operands.
#[allow(missing_docs, reason = "generated")]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum OperandAccess {
    Read,
    Write,
}

/// Operand schema metadata (kind/role/encoding).
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub struct OperandSchema {
    /// Operand kind (semantic type).
    pub kind: OperandKind,
    /// Operand role (how this operand is used).
    pub role: OperandRole,
    /// Operand encoding used by the bytecode codec.
    pub encoding: OperandEncoding,
    /// Operand access, if this is a register operand.
    pub access: Option<OperandAccess>,
}

impl OperandSchema {
    const fn new(kind: OperandKind, role: OperandRole, encoding: OperandEncoding, access: Option<OperandAccess>) -> Self {
        Self { kind, role, encoding, access }
    }
}

/// Operand layout for an opcode (indices into `OPERANDS`).
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub struct OperandLayout {
    /// Start index in `OPERANDS`.
    pub start: u16,
    /// Number of operand entries.
    pub len: u8,
}

/// Flat operand schema table indexed by `OperandLayout`.
pub const OPERANDS: &[OperandSchema] = &[
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Src, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::ImmU32, OperandRole::TrapCode, OperandEncoding::U32Uleb, None),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::ImmBool, OperandRole::Imm, OperandEncoding::BoolU8, None),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::ImmI64, OperandRole::Imm, OperandEncoding::I64Sleb, None),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::ImmU64, OperandRole::Imm, OperandEncoding::U64Uleb, None),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::ImmU64, OperandRole::Bits, OperandEncoding::U64Le, None),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::ImmI64, OperandRole::Mantissa, OperandEncoding::I64Sleb, None),
    OperandSchema::new(OperandKind::ImmU8, OperandRole::Scale, OperandEncoding::U8Raw, None),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::ConstId, OperandRole::Const, OperandEncoding::U32Uleb, None),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Cond, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Cond, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Pc, OperandRole::PcTrue, OperandEncoding::U32Uleb, None),
    OperandSchema::new(OperandKind::Pc, OperandRole::PcFalse, OperandEncoding::U32Uleb, None),
    OperandSchema::new(OperandKind::Pc, OperandRole::PcTarget, OperandEncoding::U32Uleb, None),
    OperandSchema::new(OperandKind::Reg, OperandRole::EffOut, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::FuncId, OperandRole::Func, OperandEncoding::U32Uleb, None),
    OperandSchema::new(OperandKind::Reg, OperandRole::EffIn, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::RegList, OperandRole::Args, OperandEncoding::RegListU32UlebCountThenRegs, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::RegList, OperandRole::Rets, OperandEncoding::RegListU32UlebCountThenRegs, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::EffIn, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::RegList, OperandRole::Rets, OperandEncoding::RegListU32UlebCountThenRegs, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::EffOut, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::HostSigId, OperandRole::HostSig, OperandEncoding::U32Uleb, None),
    OperandSchema::new(OperandKind::Reg, OperandRole::EffIn, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::RegList, OperandRole::Args, OperandEncoding::RegListU32UlebCountThenRegs, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::RegList, OperandRole::Rets, OperandEncoding::RegListU32UlebCountThenRegs, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::FuncId, OperandRole::Func, OperandEncoding::U32Uleb, None),
    OperandSchema::new(OperandKind::Reg, OperandRole::EffOut, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::ImmU32, OperandRole::Imm, OperandEncoding::U32Uleb, None),
    OperandSchema::new(OperandKind::Reg, OperandRole::Src, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::EffIn, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::RegList, OperandRole::Args, OperandEncoding::RegListU32UlebCountThenRegs, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::RegList, OperandRole::Rets, OperandEncoding::RegListU32UlebCountThenRegs, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Func, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Src, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::RegList, OperandRole::Values, OperandEncoding::RegListU32UlebCountThenRegs, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Tuple, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::ImmU32, OperandRole::Index, OperandEncoding::U32Uleb, None),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::TypeId, OperandRole::Type, OperandEncoding::U32Uleb, None),
    OperandSchema::new(OperandKind::RegList, OperandRole::Values, OperandEncoding::RegListU32UlebCountThenRegs, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::St, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::ImmU32, OperandRole::FieldIndex, OperandEncoding::U32Uleb, None),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::ElemTypeId, OperandRole::ElemType, OperandEncoding::U32Uleb, None),
    OperandSchema::new(OperandKind::RegList, OperandRole::Values, OperandEncoding::RegListU32UlebCountThenRegs, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Arr, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Arr, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Index, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Tuple, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::St, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Arr, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::ImmU32, OperandRole::Index, OperandEncoding::U32Uleb, None),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Bytes, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::S, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::ImmU8, OperandRole::Scale, OperandEncoding::U8Raw, None),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::ImmU8, OperandRole::Scale, OperandEncoding::U8Raw, None),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Bytes, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Index, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Bytes, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::ImmU32, OperandRole::Index, OperandEncoding::U32Uleb, None),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Bytes, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Start, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::End, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::S, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Start, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::End, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::S, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Bytes, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::B, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
    OperandSchema::new(OperandKind::Reg, OperandRole::Dst, OperandEncoding::RegU32Uleb, Some(OperandAccess::Write)),
    OperandSchema::new(OperandKind::Reg, OperandRole::A, OperandEncoding::RegU32Uleb, Some(OperandAccess::Read)),
];

/// Per-opcode metadata used by decode, disasm, and verification.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub struct OpcodeInfo {
    /// Stable, parseable opcode name.
    pub mnemonic: &'static str,
    /// Whether this opcode terminates the current basic block.
    pub is_terminator: bool,
    /// Optional per-opcode traits.
    pub flags: OpcodeFlags,
    /// Operand layout for this opcode.
    pub operands: OperandLayout,
}

/// Optional per-opcode traits.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(transparent)]
pub struct OpcodeFlags(u8);

impl OpcodeFlags {
    /// No flags set.
    pub const NONE: Self = Self(0);
    /// Call-like instruction (`call`, `host_call`, `ret`).
    pub const CALL_LIKE: Self = Self(1 << 0);

    /// Returns `true` if `other` is a subset of `self`.
    #[must_use]
    pub const fn contains(self, other: Self) -> bool {
        (self.0 & other.0) == other.0
    }
}

/// Metadata indexed by opcode byte.
pub const OPCODE_INFO_BY_BYTE: &[OpcodeInfo] = &[
    OpcodeInfo { mnemonic: "nop", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x00 Nop
    OpcodeInfo { mnemonic: "mov", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 2 } }, // 0x01 Mov
    OpcodeInfo { mnemonic: "trap", is_terminator: true, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 2, len: 1 } }, // 0x02 Trap
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x03
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x04
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x05
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x06
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x07
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x08
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x09
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x0A
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x0B
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x0C
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x0D
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x0E
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x0F
    OpcodeInfo { mnemonic: "const.unit", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 3, len: 1 } }, // 0x10 ConstUnit
    OpcodeInfo { mnemonic: "const.bool", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 4, len: 2 } }, // 0x11 ConstBool
    OpcodeInfo { mnemonic: "const.i64", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 6, len: 2 } }, // 0x12 ConstI64
    OpcodeInfo { mnemonic: "const.u64", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 8, len: 2 } }, // 0x13 ConstU64
    OpcodeInfo { mnemonic: "const.f64", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 10, len: 2 } }, // 0x14 ConstF64
    OpcodeInfo { mnemonic: "const.decimal", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 12, len: 3 } }, // 0x15 ConstDecimal
    OpcodeInfo { mnemonic: "const.pool", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 15, len: 2 } }, // 0x16 ConstPool
    OpcodeInfo { mnemonic: "dec.add", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 17, len: 3 } }, // 0x17 DecAdd
    OpcodeInfo { mnemonic: "dec.sub", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 20, len: 3 } }, // 0x18 DecSub
    OpcodeInfo { mnemonic: "dec.mul", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 23, len: 3 } }, // 0x19 DecMul
    OpcodeInfo { mnemonic: "f64.add", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 26, len: 3 } }, // 0x1A F64Add
    OpcodeInfo { mnemonic: "f64.sub", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 29, len: 3 } }, // 0x1B F64Sub
    OpcodeInfo { mnemonic: "f64.mul", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 32, len: 3 } }, // 0x1C F64Mul
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x1D
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x1E
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x1F
    OpcodeInfo { mnemonic: "i64.add", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 35, len: 3 } }, // 0x20 I64Add
    OpcodeInfo { mnemonic: "i64.sub", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 38, len: 3 } }, // 0x21 I64Sub
    OpcodeInfo { mnemonic: "i64.mul", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 41, len: 3 } }, // 0x22 I64Mul
    OpcodeInfo { mnemonic: "u64.add", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 44, len: 3 } }, // 0x23 U64Add
    OpcodeInfo { mnemonic: "u64.sub", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 47, len: 3 } }, // 0x24 U64Sub
    OpcodeInfo { mnemonic: "u64.mul", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 50, len: 3 } }, // 0x25 U64Mul
    OpcodeInfo { mnemonic: "u64.and", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 53, len: 3 } }, // 0x26 U64And
    OpcodeInfo { mnemonic: "u64.or", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 56, len: 3 } }, // 0x27 U64Or
    OpcodeInfo { mnemonic: "i64.eq", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 59, len: 3 } }, // 0x28 I64Eq
    OpcodeInfo { mnemonic: "i64.lt", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 62, len: 3 } }, // 0x29 I64Lt
    OpcodeInfo { mnemonic: "u64.eq", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 65, len: 3 } }, // 0x2A U64Eq
    OpcodeInfo { mnemonic: "u64.lt", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 68, len: 3 } }, // 0x2B U64Lt
    OpcodeInfo { mnemonic: "u64.xor", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 71, len: 3 } }, // 0x2C U64Xor
    OpcodeInfo { mnemonic: "u64.shl", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 74, len: 3 } }, // 0x2D U64Shl
    OpcodeInfo { mnemonic: "u64.shr", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 77, len: 3 } }, // 0x2E U64Shr
    OpcodeInfo { mnemonic: "u64.gt", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 80, len: 3 } }, // 0x2F U64Gt
    OpcodeInfo { mnemonic: "bool.not", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 83, len: 2 } }, // 0x30 BoolNot
    OpcodeInfo { mnemonic: "u64.le", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 85, len: 3 } }, // 0x31 U64Le
    OpcodeInfo { mnemonic: "u64.ge", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 88, len: 3 } }, // 0x32 U64Ge
    OpcodeInfo { mnemonic: "i64.and", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 91, len: 3 } }, // 0x33 I64And
    OpcodeInfo { mnemonic: "u64.to_i64", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 94, len: 2 } }, // 0x34 U64ToI64
    OpcodeInfo { mnemonic: "i64.to_u64", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 96, len: 2 } }, // 0x35 I64ToU64
    OpcodeInfo { mnemonic: "i64.or", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 98, len: 3 } }, // 0x36 I64Or
    OpcodeInfo { mnemonic: "i64.xor", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 101, len: 3 } }, // 0x37 I64Xor
    OpcodeInfo { mnemonic: "select", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 104, len: 4 } }, // 0x38 Select
    OpcodeInfo { mnemonic: "i64.gt", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 108, len: 3 } }, // 0x39 I64Gt
    OpcodeInfo { mnemonic: "i64.le", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 111, len: 3 } }, // 0x3A I64Le
    OpcodeInfo { mnemonic: "i64.ge", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 114, len: 3 } }, // 0x3B I64Ge
    OpcodeInfo { mnemonic: "i64.shl", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 117, len: 3 } }, // 0x3C I64Shl
    OpcodeInfo { mnemonic: "i64.shr", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 120, len: 3 } }, // 0x3D I64Shr
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x3E
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x3F
    OpcodeInfo { mnemonic: "br", is_terminator: true, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 123, len: 3 } }, // 0x40 Br
    OpcodeInfo { mnemonic: "jmp", is_terminator: true, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 126, len: 1 } }, // 0x41 Jmp
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x42
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x43
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x44
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x45
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x46
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x47
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x48
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x49
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x4A
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x4B
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x4C
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x4D
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x4E
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x4F
    OpcodeInfo { mnemonic: "call", is_terminator: false, flags: OpcodeFlags::CALL_LIKE, operands: OperandLayout { start: 127, len: 5 } }, // 0x50 Call
    OpcodeInfo { mnemonic: "ret", is_terminator: true, flags: OpcodeFlags::CALL_LIKE, operands: OperandLayout { start: 132, len: 2 } }, // 0x51 Ret
    OpcodeInfo { mnemonic: "host_call", is_terminator: false, flags: OpcodeFlags::CALL_LIKE, operands: OperandLayout { start: 134, len: 5 } }, // 0x52 HostCall
    OpcodeInfo { mnemonic: "const.func", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 139, len: 2 } }, // 0x53 ConstFunc
    OpcodeInfo { mnemonic: "call.indirect", is_terminator: false, flags: OpcodeFlags::CALL_LIKE, operands: OperandLayout { start: 141, len: 6 } }, // 0x54 CallIndirect
    OpcodeInfo { mnemonic: "closure.new", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 147, len: 3 } }, // 0x55 ClosureNew
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x56
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x57
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x58
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x59
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x5A
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x5B
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x5C
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x5D
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x5E
    OpcodeInfo { mnemonic: "<invalid>", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 0, len: 0 } }, // 0x5F
    OpcodeInfo { mnemonic: "tuple.new", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 150, len: 2 } }, // 0x60 TupleNew
    OpcodeInfo { mnemonic: "tuple.get", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 152, len: 3 } }, // 0x61 TupleGet
    OpcodeInfo { mnemonic: "struct.new", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 155, len: 3 } }, // 0x62 StructNew
    OpcodeInfo { mnemonic: "struct.get", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 158, len: 3 } }, // 0x63 StructGet
    OpcodeInfo { mnemonic: "array.new", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 161, len: 3 } }, // 0x64 ArrayNew
    OpcodeInfo { mnemonic: "array.len", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 164, len: 2 } }, // 0x65 ArrayLen
    OpcodeInfo { mnemonic: "array.get", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 166, len: 3 } }, // 0x66 ArrayGet
    OpcodeInfo { mnemonic: "tuple.len", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 169, len: 2 } }, // 0x67 TupleLen
    OpcodeInfo { mnemonic: "struct.field_count", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 171, len: 2 } }, // 0x68 StructFieldCount
    OpcodeInfo { mnemonic: "array.get_imm", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 173, len: 3 } }, // 0x69 ArrayGetImm
    OpcodeInfo { mnemonic: "bytes.len", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 176, len: 2 } }, // 0x6A BytesLen
    OpcodeInfo { mnemonic: "str.len", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 178, len: 2 } }, // 0x6B StrLen
    OpcodeInfo { mnemonic: "i64.div", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 180, len: 3 } }, // 0x6C I64Div
    OpcodeInfo { mnemonic: "i64.rem", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 183, len: 3 } }, // 0x6D I64Rem
    OpcodeInfo { mnemonic: "u64.div", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 186, len: 3 } }, // 0x6E U64Div
    OpcodeInfo { mnemonic: "u64.rem", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 189, len: 3 } }, // 0x6F U64Rem
    OpcodeInfo { mnemonic: "i64.to_f64", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 192, len: 2 } }, // 0x70 I64ToF64
    OpcodeInfo { mnemonic: "u64.to_f64", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 194, len: 2 } }, // 0x71 U64ToF64
    OpcodeInfo { mnemonic: "f64.to_i64", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 196, len: 2 } }, // 0x72 F64ToI64
    OpcodeInfo { mnemonic: "f64.to_u64", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 198, len: 2 } }, // 0x73 F64ToU64
    OpcodeInfo { mnemonic: "dec.to_i64", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 200, len: 2 } }, // 0x74 DecToI64
    OpcodeInfo { mnemonic: "dec.to_u64", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 202, len: 2 } }, // 0x75 DecToU64
    OpcodeInfo { mnemonic: "i64.to_dec", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 204, len: 3 } }, // 0x76 I64ToDec
    OpcodeInfo { mnemonic: "u64.to_dec", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 207, len: 3 } }, // 0x77 U64ToDec
    OpcodeInfo { mnemonic: "bytes.eq", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 210, len: 3 } }, // 0x78 BytesEq
    OpcodeInfo { mnemonic: "str.eq", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 213, len: 3 } }, // 0x79 StrEq
    OpcodeInfo { mnemonic: "bytes.concat", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 216, len: 3 } }, // 0x7A BytesConcat
    OpcodeInfo { mnemonic: "str.concat", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 219, len: 3 } }, // 0x7B StrConcat
    OpcodeInfo { mnemonic: "bytes.get", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 222, len: 3 } }, // 0x7C BytesGet
    OpcodeInfo { mnemonic: "bytes.get_imm", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 225, len: 3 } }, // 0x7D BytesGetImm
    OpcodeInfo { mnemonic: "bytes.slice", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 228, len: 4 } }, // 0x7E BytesSlice
    OpcodeInfo { mnemonic: "str.slice", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 232, len: 4 } }, // 0x7F StrSlice
    OpcodeInfo { mnemonic: "str.to_bytes", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 236, len: 2 } }, // 0x80 StrToBytes
    OpcodeInfo { mnemonic: "bytes.to_str", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 238, len: 2 } }, // 0x81 BytesToStr
    OpcodeInfo { mnemonic: "f64.div", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 240, len: 3 } }, // 0x82 F64Div
    OpcodeInfo { mnemonic: "f64.eq", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 243, len: 3 } }, // 0x83 F64Eq
    OpcodeInfo { mnemonic: "f64.lt", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 246, len: 3 } }, // 0x84 F64Lt
    OpcodeInfo { mnemonic: "f64.gt", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 249, len: 3 } }, // 0x85 F64Gt
    OpcodeInfo { mnemonic: "f64.le", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 252, len: 3 } }, // 0x86 F64Le
    OpcodeInfo { mnemonic: "f64.ge", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 255, len: 3 } }, // 0x87 F64Ge
    OpcodeInfo { mnemonic: "bool.and", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 258, len: 3 } }, // 0x88 BoolAnd
    OpcodeInfo { mnemonic: "bool.or", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 261, len: 3 } }, // 0x89 BoolOr
    OpcodeInfo { mnemonic: "bool.xor", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 264, len: 3 } }, // 0x8A BoolXor
    OpcodeInfo { mnemonic: "f64.neg", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 267, len: 2 } }, // 0x8B F64Neg
    OpcodeInfo { mnemonic: "f64.abs", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 269, len: 2 } }, // 0x8C F64Abs
    OpcodeInfo { mnemonic: "f64.min", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 271, len: 3 } }, // 0x8D F64Min
    OpcodeInfo { mnemonic: "f64.max", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 274, len: 3 } }, // 0x8E F64Max
    OpcodeInfo { mnemonic: "f64.min_num", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 277, len: 3 } }, // 0x8F F64MinNum
    OpcodeInfo { mnemonic: "f64.max_num", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 280, len: 3 } }, // 0x90 F64MaxNum
    OpcodeInfo { mnemonic: "f64.rem", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 283, len: 3 } }, // 0x91 F64Rem
    OpcodeInfo { mnemonic: "f64.to_bits", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 286, len: 2 } }, // 0x92 F64ToBits
    OpcodeInfo { mnemonic: "f64.from_bits", is_terminator: false, flags: OpcodeFlags::NONE, operands: OperandLayout { start: 288, len: 2 } }, // 0x93 F64FromBits
];

/// Bytecode opcode byte for the v1 instruction set.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum Opcode {
    /// No-op.
    Nop = 0x00,
    /// `dst = src`.
    Mov = 0x01,
    /// Trap unconditionally with a trap code.
    Trap = 0x02,
    /// `dst = ()`.
    ConstUnit = 0x10,
    /// `dst = bool`.
    ConstBool = 0x11,
    /// `dst = i64`.
    ConstI64 = 0x12,
    /// `dst = u64`.
    ConstU64 = 0x13,
    /// `dst = f64` encoded as raw IEEE bits.
    ConstF64 = 0x14,
    /// `dst = Decimal { mantissa, scale }`.
    ConstDecimal = 0x15,
    /// `dst = const_pool[idx]`.
    ConstPool = 0x16,
    /// `dst = a + b` (`Decimal`).
    DecAdd = 0x17,
    /// `dst = a - b` (`Decimal`).
    DecSub = 0x18,
    /// `dst = a * b` (`Decimal`).
    DecMul = 0x19,
    /// `dst = a + b` (`f64`).
    F64Add = 0x1A,
    /// `dst = a - b` (`f64`).
    F64Sub = 0x1B,
    /// `dst = a * b` (`f64`).
    F64Mul = 0x1C,
    /// `dst = a + b` (`i64`).
    I64Add = 0x20,
    /// `dst = a - b` (`i64`).
    I64Sub = 0x21,
    /// `dst = a * b` (`i64`).
    I64Mul = 0x22,
    /// `dst = a + b` (`u64`).
    U64Add = 0x23,
    /// `dst = a - b` (`u64`).
    U64Sub = 0x24,
    /// `dst = a * b` (`u64`).
    U64Mul = 0x25,
    /// `dst = a & b` (`u64`).
    U64And = 0x26,
    /// `dst = a | b` (`u64`).
    U64Or = 0x27,
    /// `dst = (a == b)` (`i64` -> `bool`).
    I64Eq = 0x28,
    /// `dst = (a < b)` (`i64` -> `bool`).
    I64Lt = 0x29,
    /// `dst = (a == b)` (`u64` -> `bool`).
    U64Eq = 0x2A,
    /// `dst = (a < b)` (`u64` -> `bool`).
    U64Lt = 0x2B,
    /// `dst = a ^ b` (`u64`).
    U64Xor = 0x2C,
    /// `dst = a << (b & 63)` (`u64`).
    U64Shl = 0x2D,
    /// `dst = a >> (b & 63)` (`u64`).
    U64Shr = 0x2E,
    /// `dst = (a > b)` (`u64` -> `bool`).
    U64Gt = 0x2F,
    /// `dst = !a` (`bool`).
    BoolNot = 0x30,
    /// `dst = (a <= b)` (`u64` -> `bool`).
    U64Le = 0x31,
    /// `dst = (a >= b)` (`u64` -> `bool`).
    U64Ge = 0x32,
    /// `dst = a & b` (`i64`).
    I64And = 0x33,
    /// `dst = u64_to_i64(a)` (traps on overflow).
    U64ToI64 = 0x34,
    /// `dst = i64_to_u64(a)` (traps on negative).
    I64ToU64 = 0x35,
    /// `dst = a | b` (`i64`).
    I64Or = 0x36,
    /// `dst = a ^ b` (`i64`).
    I64Xor = 0x37,
    /// `dst = if cond { a } else { b }`.
    Select = 0x38,
    /// `dst = (a > b)` (`i64` -> `bool`).
    I64Gt = 0x39,
    /// `dst = (a <= b)` (`i64` -> `bool`).
    I64Le = 0x3A,
    /// `dst = (a >= b)` (`i64` -> `bool`).
    I64Ge = 0x3B,
    /// `dst = a << (b & 63)` (`i64`).
    I64Shl = 0x3C,
    /// `dst = a >> (b & 63)` (`i64`).
    I64Shr = 0x3D,
    /// Branch based on `cond` to `pc_true` or `pc_false` (byte offsets).
    Br = 0x40,
    /// Jump to `pc_target` (byte offset).
    Jmp = 0x41,
    /// Call a function.
    Call = 0x50,
    /// Return from the current function.
    Ret = 0x51,
    /// Call a host function.
    HostCall = 0x52,
    /// `dst = func#func_id`.
    ConstFunc = 0x53,
    /// Call a callee value in a register, checked against a call signature.
    CallIndirect = 0x54,
    /// Construct a closure from a function value register and env aggregate register.
    ClosureNew = 0x55,
    /// Allocate a tuple aggregate.
    TupleNew = 0x60,
    /// Read tuple element at an immediate index.
    TupleGet = 0x61,
    /// Allocate a struct aggregate.
    StructNew = 0x62,
    /// Read struct field at an immediate index.
    StructGet = 0x63,
    /// Allocate an array aggregate.
    ArrayNew = 0x64,
    /// Read array length.
    ArrayLen = 0x65,
    /// Read array element at an index register.
    ArrayGet = 0x66,
    /// Read tuple length.
    TupleLen = 0x67,
    /// Read struct field count.
    StructFieldCount = 0x68,
    /// Read array element at an immediate index.
    ArrayGetImm = 0x69,
    /// Read byte-string length.
    BytesLen = 0x6A,
    /// Read UTF-8 string length (in bytes).
    StrLen = 0x6B,
    /// `dst = a / b` (`i64`, traps on divide-by-zero and `i64::MIN / -1`).
    I64Div = 0x6C,
    /// `dst = a % b` (`i64`, traps on divide-by-zero and `i64::MIN % -1`).
    I64Rem = 0x6D,
    /// `dst = a / b` (`u64`, traps on divide-by-zero).
    U64Div = 0x6E,
    /// `dst = a % b` (`u64`, traps on divide-by-zero).
    U64Rem = 0x6F,
    /// `dst = (a as f64)` (`i64` to `f64`).
    I64ToF64 = 0x70,
    /// `dst = (a as f64)` (`u64` to `f64`).
    U64ToF64 = 0x71,
    /// `dst = trunc(a)` (`f64` to `i64`, traps on NaN/inf/out-of-range).
    F64ToI64 = 0x72,
    /// `dst = trunc(a)` (`f64` to `u64`, traps on NaN/inf/out-of-range/negative).
    F64ToU64 = 0x73,
    /// `dst = a.mantissa` (`Decimal` to `i64`, traps if `scale != 0`).
    DecToI64 = 0x74,
    /// `dst = a.mantissa` (`Decimal` to `u64`, traps if `scale != 0` or mantissa < 0).
    DecToU64 = 0x75,
    /// `dst = Decimal { mantissa: a * 10^scale, scale }` (traps on overflow).
    I64ToDec = 0x76,
    /// `dst = Decimal { mantissa: a * 10^scale, scale }` (traps on overflow).
    U64ToDec = 0x77,
    /// `dst = (a == b)` (`bytes` -> `bool`).
    BytesEq = 0x78,
    /// `dst = (a == b)` (`str` -> `bool`).
    StrEq = 0x79,
    /// `dst = concat(a, b)` (`bytes`).
    BytesConcat = 0x7A,
    /// `dst = concat(a, b)` (`str`).
    StrConcat = 0x7B,
    /// `dst = bytes[index]` (returns `u64` in `0..=255`, traps on OOB).
    BytesGet = 0x7C,
    /// `dst = bytes[index]` (returns `u64` in `0..=255`, traps on OOB).
    BytesGetImm = 0x7D,
    /// `dst = bytes[start..end]` (traps on invalid range).
    BytesSlice = 0x7E,
    /// `dst = s[start..end]` (byte indices; traps on invalid range or non-boundaries).
    StrSlice = 0x7F,
    /// `dst = s.as_bytes().to_vec()`.
    StrToBytes = 0x80,
    /// `dst = String::from_utf8(bytes)` (traps on invalid UTF-8).
    BytesToStr = 0x81,
    /// `dst = a / b` (`f64`).
    F64Div = 0x82,
    /// `dst = (a == b)` (`f64` -> `bool`).
    F64Eq = 0x83,
    /// `dst = (a < b)` (`f64` -> `bool`).
    F64Lt = 0x84,
    /// `dst = (a > b)` (`f64` -> `bool`).
    F64Gt = 0x85,
    /// `dst = (a <= b)` (`f64` -> `bool`).
    F64Le = 0x86,
    /// `dst = (a >= b)` (`f64` -> `bool`).
    F64Ge = 0x87,
    /// `dst = a & b` (`bool`).
    BoolAnd = 0x88,
    /// `dst = a | b` (`bool`).
    BoolOr = 0x89,
    /// `dst = a ^ b` (`bool`).
    BoolXor = 0x8A,
    /// `dst = -a` (`f64`).
    F64Neg = 0x8B,
    /// `dst = abs(a)` (`f64`).
    F64Abs = 0x8C,
    /// `dst = min(a, b)` (`f64`, NaN-propagating).
    F64Min = 0x8D,
    /// `dst = max(a, b)` (`f64`, NaN-propagating).
    F64Max = 0x8E,
    /// `dst = min_num(a, b)` (`f64`, number-favoring).
    F64MinNum = 0x8F,
    /// `dst = max_num(a, b)` (`f64`, number-favoring).
    F64MaxNum = 0x90,
    /// `dst = a % b` (`f64`).
    F64Rem = 0x91,
    /// `dst = f64_to_bits(a)` (`f64` -> `u64`).
    F64ToBits = 0x92,
    /// `dst = f64_from_bits(a)` (`u64` -> `f64`).
    F64FromBits = 0x93,
}

impl Opcode {
    /// Decodes an opcode byte.
    #[must_use]
    pub fn from_u8(b: u8) -> Option<Self> {
        Some(match b {
            0x00 => Self::Nop,
            0x01 => Self::Mov,
            0x02 => Self::Trap,
            0x10 => Self::ConstUnit,
            0x11 => Self::ConstBool,
            0x12 => Self::ConstI64,
            0x13 => Self::ConstU64,
            0x14 => Self::ConstF64,
            0x15 => Self::ConstDecimal,
            0x16 => Self::ConstPool,
            0x17 => Self::DecAdd,
            0x18 => Self::DecSub,
            0x19 => Self::DecMul,
            0x1A => Self::F64Add,
            0x1B => Self::F64Sub,
            0x1C => Self::F64Mul,
            0x20 => Self::I64Add,
            0x21 => Self::I64Sub,
            0x22 => Self::I64Mul,
            0x23 => Self::U64Add,
            0x24 => Self::U64Sub,
            0x25 => Self::U64Mul,
            0x26 => Self::U64And,
            0x27 => Self::U64Or,
            0x28 => Self::I64Eq,
            0x29 => Self::I64Lt,
            0x2A => Self::U64Eq,
            0x2B => Self::U64Lt,
            0x2C => Self::U64Xor,
            0x2D => Self::U64Shl,
            0x2E => Self::U64Shr,
            0x2F => Self::U64Gt,
            0x30 => Self::BoolNot,
            0x31 => Self::U64Le,
            0x32 => Self::U64Ge,
            0x33 => Self::I64And,
            0x34 => Self::U64ToI64,
            0x35 => Self::I64ToU64,
            0x36 => Self::I64Or,
            0x37 => Self::I64Xor,
            0x38 => Self::Select,
            0x39 => Self::I64Gt,
            0x3A => Self::I64Le,
            0x3B => Self::I64Ge,
            0x3C => Self::I64Shl,
            0x3D => Self::I64Shr,
            0x40 => Self::Br,
            0x41 => Self::Jmp,
            0x50 => Self::Call,
            0x51 => Self::Ret,
            0x52 => Self::HostCall,
            0x53 => Self::ConstFunc,
            0x54 => Self::CallIndirect,
            0x55 => Self::ClosureNew,
            0x60 => Self::TupleNew,
            0x61 => Self::TupleGet,
            0x62 => Self::StructNew,
            0x63 => Self::StructGet,
            0x64 => Self::ArrayNew,
            0x65 => Self::ArrayLen,
            0x66 => Self::ArrayGet,
            0x67 => Self::TupleLen,
            0x68 => Self::StructFieldCount,
            0x69 => Self::ArrayGetImm,
            0x6A => Self::BytesLen,
            0x6B => Self::StrLen,
            0x6C => Self::I64Div,
            0x6D => Self::I64Rem,
            0x6E => Self::U64Div,
            0x6F => Self::U64Rem,
            0x70 => Self::I64ToF64,
            0x71 => Self::U64ToF64,
            0x72 => Self::F64ToI64,
            0x73 => Self::F64ToU64,
            0x74 => Self::DecToI64,
            0x75 => Self::DecToU64,
            0x76 => Self::I64ToDec,
            0x77 => Self::U64ToDec,
            0x78 => Self::BytesEq,
            0x79 => Self::StrEq,
            0x7A => Self::BytesConcat,
            0x7B => Self::StrConcat,
            0x7C => Self::BytesGet,
            0x7D => Self::BytesGetImm,
            0x7E => Self::BytesSlice,
            0x7F => Self::StrSlice,
            0x80 => Self::StrToBytes,
            0x81 => Self::BytesToStr,
            0x82 => Self::F64Div,
            0x83 => Self::F64Eq,
            0x84 => Self::F64Lt,
            0x85 => Self::F64Gt,
            0x86 => Self::F64Le,
            0x87 => Self::F64Ge,
            0x88 => Self::BoolAnd,
            0x89 => Self::BoolOr,
            0x8A => Self::BoolXor,
            0x8B => Self::F64Neg,
            0x8C => Self::F64Abs,
            0x8D => Self::F64Min,
            0x8E => Self::F64Max,
            0x8F => Self::F64MinNum,
            0x90 => Self::F64MaxNum,
            0x91 => Self::F64Rem,
            0x92 => Self::F64ToBits,
            0x93 => Self::F64FromBits,
            _ => return None,
        })
    }

    /// Returns `true` if this opcode terminates the current basic block.
    #[must_use]
    pub fn is_terminator(self) -> bool {
        self.info().is_terminator
    }

    /// Stable, parseable opcode name.
    ///
    /// This string is used by the disassembler output.
    #[must_use]
    pub fn mnemonic(self) -> &'static str {
        self.info().mnemonic
    }

    /// Returns opcode metadata for this opcode.
    #[must_use]
    pub fn info(self) -> &'static OpcodeInfo {
        &OPCODE_INFO_BY_BYTE[usize::from(self as u8)]
    }

    /// Returns `true` if this opcode is call-like.
    #[must_use]
    pub fn is_call_like(self) -> bool {
        self.info().flags.contains(OpcodeFlags::CALL_LIKE)
    }

    /// Returns operand schema descriptors for this opcode.
    #[must_use]
    pub fn operands(self) -> &'static [OperandSchema] {
        let layout = self.info().operands;
        let start = usize::from(layout.start);
        let end = start + usize::from(layout.len);
        &OPERANDS[start..end]
    }
}
